[project]
name = "pyperformance_bm_fast_crypto"
requires-python = ">=3.8"
dependencies = [
  "pyperf",
  "cryptography",
]
dynamic = ["version"]
urls = { repository = "https://github.com/python/pyperformance" }

[tool.pyperformance]
name = "fast_crypto"
